import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Homepage.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Homepage}>
        <Image
          className={styles.image}
          src="https://i.pinimg.com/originals/6b/9f/be/6b9fbe557b67bcb6316a23cddad1a90d.jpg"
          alt="pokemon"
          width="1000"
          height="600"
        />
      </div>
    </>
  );
}
